version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./storage-data:/var/www/html/storage/app/public
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    restart: always
